site_name: OpenFlexure Microscope OpenScad Docs
nav:
  - Alphabetical Index: alphaindex.md
  - Repository: https://gitlab.com/openflexure/openflexure-microscope/
docs_dir: openscad-docs
extra_css:
  - css/style.css
markdown_extensions:
  - markdown.extensions.extra
theme:
  name: mkdocs
  custom_dir: mkdocs_theme
  navigation_depth: 3

